name: bucketlistappfullstack
services:
    bucketlistapi:
        stdin_open: true
        tty: true
        ports:
            - 8080:8080
        image: bucketlistapi

    bucketlistapp:
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
        image: bucketlistapp

    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  bucketlistapi:
